name: checkpoint Pipeline

on:
  push:
    branches: [eli]

jobs:
  sha-guard-01:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: sha-check
        run: echo "running zizmor scan"

      - name: Install and Check hash
        run: python3 -m pip install --require-hashes -r requirements-zizmor.txt

      - name: Scan all yml files
        run: |
          zizmor .github/workflows --format text
          zizmor .github/archive --format text

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
           role-to-assume: arn:aws:iam::$ACCOUNT_ID:role/checkpoint-github-actions
           aws-region: us-east-1



  contraband-checkguard-02:
    needs: sha-guard-01
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Pull docker image
        run: |
          docker pull ghcr.io/${{ github.repository }}:latest

      - name: Image-scan
        run: |
